pipeline:
  name: cicd-gitops-pipeline
  identifier: cicdgitopspipeline
  projectIdentifier: defualt
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnector
        build: <+input>
  stages:
    - stage:
        name: ci-stage
        identifier: cistage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Powershell
                    command: npm install
  variables:
    - name: imageRepo
      type: String
      description: ""
      required: false
      value: abhi2244/hellotestforharness
    - name: imageTag
      type: String
      description: ""
      required: false
      value: latest
